### PR TITLE
Add support for installation of nvidia proprietary drivers on user opting in.

### PR DESCRIPTION
**Pull request by ElectroPerf**

### CODE REVIEW

**Comment by ElectroPerf** [comment]
tested on my nvidia rtx4080 super and works just fine

**Comment by mylinuxforwork** [comment]
Hi. Thanks for providing the PR. This will improve the installation a lot. Will add this to the installer in a seperate branch soon and ask more users to test it. But will change the configuration dialogue a bit. Need to add gum confirm.
Unfortunately I cannot test it on my systems. But I can run the installer on a VM.
Keep you posted.

**Comment by Houdini76** [comment]
Maybe add installation-script for Arch Linux both minimal and with Plasma 6?

**Comment by mylinuxforwork** [comment]
> Maybe add installation-script for Arch Linux both minimal and with Plasma 6?

Not sure what you request. The Dotfiles are independent from the base Arch system. Adding an installation of Arch would require an own distro. Maybe in the future.

**Comment by ElectroPerf** [comment]
> Hi. Thanks for providing the PR. This will improve the installation a lot. Will add this to the installer in a seperate branch soon and ask more users to test it. But will change the configuration dialogue a bit. Need to add gum confirm. Unfortunately I cannot test it on my systems. But I can run the installer on a VM. Keep you posted.

Great.

**Comment by mattjax16** [comment]
I can pull this branch and test as I have 3 different nvidia cards I can test it with. Ill report back tmmr with an edit about how it runs.

**Comment by mylinuxforwork** [comment]
> I can pull this branch and test as I have 3 different nvidia cards I can test it with. Ill report back tmmr with an edit about how it runs.

Great.

**Comment by ElectroPerf** [comment]
Any updates on the testing?

**Comment by mattjax16** [comment]
So sorry got bussy with school just started a CE master program. I can report back that it is indeed working with rtx3080, rtx3060ti, and gtx1070!

**Comment by mattjax16** [comment]
Anyway else I can help with testing to get this pull request accepted?

**Comment by mylinuxforwork** [comment]
> Anyway else I can help with testing to get this pull request accepted?

Need to look into it in detail. But it’s on my list for 2.9.7

**Comment by ElectroPerf** [comment]
uh seems like a forcepush nuked everything, ill push a new change

**Comment by ElectroPerf** [comment]
changed destination to #375

**Pull request closed without merging**
