### PR TITLE
Fix all the current issues with system monitor and nvidia drivers

### PR DESCRIPTION
**Pull request by ElectroPerf**
The missioncenter command wasn't correct, causing the waybar module and keybinding to do nothing on triggering mission center and all of the glitches, scaling issues with nvidia drivers are now fixed with the updated environment variables

### CODE REVIEW

**Comment by ElectroPerf** [comment]
@mylinuxforwork

**Comment by mylinuxforwork** [comment]
@ElectroPerf Awesome. Thank you. I am using AMD GPU. That's why it's always difficult to test.

**Comment by ElectroPerf** [comment]
Thankyou.. also @mylinuxforwork can u verify if the missioncenter change here is correct or does it need to be changed elsewhere in the repo? Cuz the package name is mission-center but the command is missioncenter

**Comment by mylinuxforwork** [comment]
> Thankyou.. also @mylinuxforwork can u verify if the missioncenter change here is correct or does it need to be changed elsewhere in the repo? Cuz the package name is mission-center but the command is missioncenter

Yes. The installation command is https://aur.archlinux.org/packages/mission-center

**Comment by ElectroPerf** [comment]
Great

**Pull request merged**
