### PR TITLE
some important changes

### PR DESCRIPTION
**Pull request by ElectroPerf**

### CODE REVIEW

**Review by ElectroPerf — COMMENTED** [review]
following up with #84

**Comment by ElectroPerf** [comment]
@mylinuxforwork do have a look

**Comment by ElectroPerf** [comment]
the nvidia script works with my rtx 4080 super as intended

**Comment by mylinuxforwork** [comment]
@ElectroPerf Have merged your changes into main. But commented out the NVIDIA script. I need to rework a bit. AUR helper needs to be flexible: yay or paru. I also need to test it in a VM first and add a parameter to the automation.sh script.

**Comment by mylinuxforwork** [comment]
@ElectroPerf I have just pushed an update to the main branch. Can you update your ML4W Dotfiles with yay -S ml4w-hyprland-git and then execute ml4w-hyprland-setup -m nvidia

This should execute your script during the installation procedure. Would be great if you could test it.

**Comment by ElectroPerf** [comment]
@mylinuxforwork I'll give it a go soon

**Comment by ElectroPerf** [comment]
@mylinuxforwork i did check it and it works fine

**Comment by mylinuxforwork** [comment]
@ElectroPerf Great. Grub bootloader is required for this setup, correct? Is it working with systemd boot as well?
https://github.com/mylinuxforwork/dotfiles/blob/main/lib/install/nvidia.sh

**Comment by ElectroPerf** [comment]
Yea grub is required

**Comment by ElectroPerf** [comment]
No idea about systemd, i never use it neither is this cmd supposed to be there with systemd

**Pull request merged**
